In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
a=np.arange(1,101)
b=np.arange(501,601)

In [4]:
train_test_split(a, shuffle=False)

[array([45, 58, 54, 15, 51, 52, 37, 39,  3, 50, 95, 81, 53, 22, 30, 92,  8,
        47, 73, 17, 23, 98, 46, 18, 71, 85, 76, 83, 74, 26, 13, 28, 56, 57,
        87, 21, 43, 64, 82, 42, 67, 97, 69, 91, 94, 10, 80,  5, 31,  4, 40,
        68,  1, 44, 88, 61, 29, 86, 41, 59, 89, 99,  7,  6, 84, 90, 72, 32,
        62,  9, 38, 27, 33, 65, 75]),
 array([ 63,  25,  20,  14,  34,  78,  60,  36,  16,   2,  35,  49,  77,
         55,  48,  96,  24,  70,  66,  11,  12,  79,  93,  19, 100])]

In [14]:
a_train, a_test ,b_train,b_test= train_test_split(a, b,test_size=0.2,shuffle=False)

ValueError: Found input variables with inconsistent numbers of samples: [100, 101]

In [11]:
a_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [12]:
a_test

array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])

In [13]:
a_train.shape,a_test.shape

((80,), (20,))