In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
data=pd.read_csv(r'C:\Users\LasimaSN\Downloads\The Data Science Course 2020 - All Resources\Part_5_Advanced_Statistical_Methods_(Machine_Learning)\S34_L210\1.01. Simple linear regression.csv')
data.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

In [6]:
x=data['SAT']
y=data['GPA']
x_matrix=x.values.reshape(-1,1)

In [7]:
reg=LinearRegression()
reg.fit(x_matrix,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
#R-squared
reg.score(x_matrix,y)

0.40600391479679765

In [10]:
#Co-efficicent
reg.coef_

array([0.00165569])

In [11]:
#Intercept
reg.intercept_

0.2750402996602803

In [13]:
#Making Predictions
reg.predict(np.array(1740).reshape(-1,1))

array([3.15593751])

In [15]:
new = pd.DataFrame(data=[1740,1760],columns=['SAT'])
new

SAT
0  1740
1  1760

In [16]:
reg.predict(new)

array([3.15593751, 3.18905127])

In [17]:
new['Predicted GPA']=reg.predict(new)

In [18]:
new

SAT  Predicted GPA
0  1740       3.155938
1  1760       3.189051

In [ ]:
plt.scatter(x,y)
yhat = reg.coef_*x_matrix + reg.intercept_
fig= plt.plt(x,yhat,lw=2,c='Green',label='regression line')
plt.xlabel('SAT',fontsize=20)
plt.ylabel('')