In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression
data=pd.read_csv(r'C:\Users\LasimaSN\Downloads\The Data Science Course 2020 - All Resources\Part_5_Advanced_Statistical_Methods_(Machine_Learning)\S34_L216\1.02. Multiple linear regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [2]:
x=data[['SAT','Rand 1,2,3']]
y=data['GPA']

In [3]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
r2=reg.score(x,y)
n= x.shape[0]
p= x.shape[1]

adj_r2= 1-(1-r2)*(n-1)/(n-p-1)
adj_r2

0.39203134825134023

In [6]:
from sklearn.feature_selection import f_regression
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [7]:
p_value = f_regression(x,y)[1]
p_value

array([7.19951844e-11, 6.76291372e-01])

In [8]:
p_value.round(3)

array([0.   , 0.676])

In [12]:
reg_summary= pd.DataFrame(data= x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [14]:
reg_summary['Co-efficients']=reg.coef_
reg_summary['P-values']=p_value.round(3)
reg_summary

Features  Co-efficients  P-values
0         SAT       0.001654     0.000
1  Rand 1,2,3      -0.008270     0.676